version: '3.8'

services:
  mainDB:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./vol:/db/main
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DATABASE_USERNAME}', '-d', '${DATABASE_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: nestjs-backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      mainDB:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    container_name: vite-frontend
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
