services:
  mainDB:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./vol:/db/main
    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD',
          'pg_isready',
          '-U',
          '${DATABASE_USERNAME}',
          '-d',
          '${DATABASE_NAME}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
