-- Update ActivityType enum first by removing old values
ALTER TYPE "ActivityType" DROP VALUE IF EXISTS 'BOOKING';
ALTER TYPE "ActivityType" DROP VALUE IF EXISTS 'RETURN';
ALTER TYPE "ActivityType" DROP VALUE IF EXISTS 'PAYMENT';
ALTER TYPE "ActivityType" DROP VALUE IF EXISTS 'CAR_ADDED';
ALTER TYPE "ActivityType" DROP VALUE IF EXISTS 'CAR_UPDATED';

-- Add new values to ActivityType
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'USER_REGISTERED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CAR_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CAR_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CAR_DELETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'BOOKING_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'BOOKING_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'BOOKING_CANCELLED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'BOOKING_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'PAYMENT_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'REVIEW_ADDED';

-- Update PaymentProvider enum
ALTER TYPE "PaymentProvider" DROP VALUE IF EXISTS 'ZALOPAY';

-- Update activities table with new columns
ALTER TABLE "activities" 
ADD COLUMN IF NOT EXISTS "bookingId" TEXT,
ADD COLUMN IF NOT EXISTS "carId" TEXT,
ADD COLUMN IF NOT EXISTS "amount" DECIMAL,
ADD COLUMN IF NOT EXISTS "title" TEXT,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
